version: 2
jobs:
  build:
    # Build .deb package
    docker:
      - image: debian:stable
    steps:
      - checkout
      - run:
          command: |
            apt-get update -q
            apt-get install -y --no-install-recommends git python3 python3-requests
            ./.circleci/debops-ci ci

  test:
    # Deploy API + fastpath + database + ooniprobe

    docker:
      # Primary container image where all commands run
      - image: debian:stable
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/metadb

      # Service container image
      - image: circleci/postgres:11

    steps:
      - run: whoami
      - run: echo "deb [trusted=yes] https://dl.bintray.com/ooni/internal-pull-requests unstable main" | sudo tee /etc/apt/sources.list.d/bintray.list
      - run: sudo apt-get update
      - run: sudo apt-get install -y fastpath analysis ooni-api
