version: 2
# DEB_GPG_KEY is set to
# gpg --export-secret-keys B5A08F01796E7F521861B449372D1FF271F2DD50 | base64 --wrap=0
# because CircleCI cannot handle multiline env vars
jobs:
  create_deb_package:
    # Build .deb package
    docker:
      - image: debian:stable
    steps:
      - checkout
      - run: echo "deb http://deb.debian.org/debian buster-backports main" > /etc/apt/sources.list.d/backports.list
      - run: apt-get update -q
      - run: apt-get install -q -y --no-install-recommends git python3 python3-requests s3cmd python3-gnupg
      - run: |
          export DEB_GPG_KEY=$(echo $DEB_GPG_KEY | base64 -d)
          ./.circleci/debops-ci --show-commands ci --bucket-name ooni-internal-deb

  end_to_end_test:
    # Deploy API + fastpath + database + ooniprobe

    docker:
      # Primary container image where all commands run
      - image: debian:stable
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/metadb

      # Service container image
      - image: circleci/postgres:11
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - run: whoami
      - run: DEBIAN_FRONTEND=noninteractive apt-get update
      - run: DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates
      - run: echo "deb [trusted=yes] https://dl.bintray.com/ooni/internal-pull-requests unstable main" > /etc/apt/sources.list.d/bintray.list
      - run: echo "deb http://deb.debian.org/debian buster-backports main" > /etc/apt/sources.list.d/backports.list
      - run: DEBIAN_FRONTEND=noninteractive apt-get update
      - run: DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y openssh-client ssl-cert
      - run: mkdir -p /run/nodeexp/
      - run: DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y fastpath analysis ooni-api

workflows:
  version: 2

  my_workflows:
    jobs:
      - create_deb_package:
          context: ooni
      #- end_to_end_test
