db:
  image: postgres:9.6
  ports:
    - "5433:5432"

web:
  env_file:
  - ./config/base.env
  - ./config/staging.env
  - /opt/secrets.env
  ports:
    - "80:8000"
  links:
    - db

worker:
  env_file:
  - ./config/base.env
  - ./config/staging.env
  - /opt/secrets.env
  links:
    - db

beat:
  env_file:
  - ./config/base.env
  - ./config/staging.env
  - /opt/secrets.env
  links:
    - db
