db:
  image: postgres:9.6
  ports:
    - "5433:5432"

web:
  env_file:
  - ./config/base.env
  - ./config/testing.env
  - /opt/secrets.env
  volumes:
    - ./measurements:/app/measurements:z
    - ./dev:/app/dev
  ports:
    - "80:8000"
  links:
    - db

worker:
  env_file:
  - ./config/base.env
  - ./config/testing.env
  - /opt/secrets.env
  volumes:
    - ./measurements:/app/measurements:z
    - ./dev:/app/dev
  links:
    - db

beat:
  env_file:
  - ./config/base.env
  - ./config/testing.env
  - /opt/secrets.env
  volumes:
    - ./measurements:/app/measurements:z
    - ./dev:/app/dev
  links:
    - db
