name: OONI API tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: nikolaik/python-nodejs:python3.7-nodejs12-stretch
    services:
      postgres:
        image: postgres:9.6.17
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel codecov
          pip install -r requirements/main.txt
          pip install -r requirements/tests.txt
          npm install
          apt-get update && apt-get install -y postgresql-client
      - name: Init the databse
        run: bash scripts/travis_init_db.sh
      - name: Run tests
        run: make APP_ENV=production test
